name: decent_chatbot
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0  
  http: ^1.1.2
  get: ^4.6.6
  get_storage: ^2.1.1
  gap: ^3.0.1
  flutter_svg: ^2.0.9
  overlay_support: ^2.1.0
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  appinio_swiper: ^2.1.1
  loader_overlay: ^4.0.3

get:
  flutter_localizations:
    sdk: flutter
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

 
  uses-material-design: true

  assets:
   - assets/png/